# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, the root path of your project
root = "."
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/http/main.go"
  # Binary file yields from `cmd`.
  bin = "./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", ".vscode", "bin", "scripts", "docs", "migrations", "postgres", "k6", "k8s"]
  # Ignore files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = true
  # This log file places in your tmp_dir.
  log = "air.log"
  # Poll files for changes instead of using fsnotify.
  poll = false
  # Poll interval (defaults to the minimum interval of 500ms).
  poll_interval = 500
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = true
  # Delay after sending Interrupt signal.
  kill_delay = 500

[log]
  # Show log time
  time = true
  # Only show main log (hide build log)
  main_only = false

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
